name: 'Check for latest axon-bom'

on:
  workflow_dispatch:
#  schedule:
#    - cron '0 * * * *'

jobs:
  setup-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install yq package
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: show utitlity versions
        run: |
          jq --version
          yq --version
