name: 'Check for latest axon-bom'

on:
  workflow_dispatch:
#  schedule:
#    - cron '0 * * * *'

jobs:
  setup-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install yq package
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: get current known version of axon-bom
        id: versions
        run: |
          echo ::set-output name=knownVersion::$(yq e '.initializr.env.boms.axon-bom.mappings[0].version' initializr-be/src/main/resources/application.yaml)
          echo ::set-output name=latestPublishedVersion::$(curl -s https://search.maven.org/classic/solrsearch/select?q=g:org.axonframework+AND+a:axon-bom | jq -r '.response.docs[0].latestVersion')

