name: 'Check for latest axon-bom'

#run every 6 hours to see if there is a new version released.
on:
  schedule:
    - cron: '0 0,6,12,18 * * *'

jobs:
  setup-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install yq package
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: get current known version of axon-bom
        id: versions
        run: |
          echo ::set-output name=knownVersion::$(yq e '.initializr.env.boms.axon-bom.mappings[0].version' initializr-be/src/main/resources/application.yaml)
          echo ::set-output name=latestPublishedVersion::$(curl -s https://search.maven.org/classic/solrsearch/select?q=g:org.axonframework+AND+a:axon-bom | jq -r '.response.docs[0].latestVersion')

      - name: print known versions
        id: echo-versions
        run: |
          echo "The last known version is ${{ steps.versions.outputs.knownVersion }}"
          echo "The last released version is ${{ steps.versions.outputs.latestPublishedVersion }}"

      - name: Update axon-bom in application.yaml
        if: steps.versions.outputs.knownVersion != steps.versions.outputs.latestPublishedVersion
        run: |
          export latestVersion=${{ steps.versions.outputs.latestPublishedVersion }}
          yq e '.initializr.env.boms.axon-bom.mappings[0].version=env(latestVersion)' -i initializr-be/src/main/resources/application.yaml

      - name: Create PR for latest axon-bom version
        uses: peter-evans/create-pull-request@v3
        if: success() && steps.versions.outputs.knownVersion != steps.versions.outputs.latestPublishedVersion
        with:
          commit-message: update axon-bom to version ${{ steps.versions.outputs.latestPublishedVersion }}
          title: Update Axon-BOM to version ${{ steps.versions.outputs.latestPublishedVersion }}
          assignees: idugalic, brunchey
          branch: update-axon-bom-to-ver-${{ steps.versions.outputs.latestPublishedVersion }}
          labels: |
            check-axon-bom-version
            ${{ steps.versions.outputs.latestPublishedVersion }}