name: Main-Compile-Test-Build-Deploy-Image

on:
  push:
    branches:
      - main

jobs:
  setup-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Calculate short sha commit
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Setup gcloud CLI, needed to pull and push image on gcr
      - uses: google-github-actions/setup-gcloud@master
        if: github.github.head_ref == null && success()
        with:
          version: '297.0.1'
          service_account_key: ${{ secrets.GKE_DEVOPS_SA_KEY }}
          project_id: 'axoniq-devops'
          export_default_credentials: true

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - name: Maven Build
        run: |
          ./mvnw -B verify

      - name: Publish docker image to eu.gcr.io
        if: github.github.head_ref == null && success()
        run: |
          mvn -B -U -Pdocker package -DskipTests -Dimage.version=$SHA8
        env:
          SHA8: ${{ steps.vars.outputs.sha_short }}

    outputs:
      image_version: ${{ steps.vars.outputs.sha_short }}

  prepare-cd:
    name: Prepare next release.
    runs-on: ubuntu-latest

    needs: setup-build-push

    steps:
      - name: Checkout AxonIQ/initializr-deploy repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PA_TOKEN_GITHUB }}
          repository: AxonIQ/initializr-deploy
          ref: main

      - run: |
          git config user.name 'brunchey'
          git config user.email 'ben.runchey@axoniq.io'

      - name: Preapare next release
        if: github.github.head_ref == null
        run: |
          cd k8s/dev/
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          ./kustomize edit set image eu.gcr.io/axoniq-devops/axoniq-initializr=eu.gcr.io/axoniq-devops/axoniq-initializr:$IMAGE_VERSION
        env:
          IMAGE_VERSION: ${{ needs.setup-build-push.outputs.image_version }}

      - name: Push release changes
        if: github.github.head_ref == null
        run: |
          git commit -am "[initializr-deploy] Prepare next release $IMAGE_VERSION"
          git push
        env:
          IMAGE_VERSION: ${{ needs.setup-build-push.outputs.image_version }}