name: Main-Compile-Test-Build-Deploy-Image

on:
  push:

jobs:
  setup-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Calculate short sha commit
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Setup gcloud CLI, needed to pull and push image on gcr
      - uses: google-github-actions/setup-gcloud@master
        if: github.github.head_ref == null && success()
        with:
          version: '297.0.1'
          service_account_key: ${{ secrets.GKE_DEVOPS_SA_KEY }}
          project_id: 'axoniq-devops'
          export_default_credentials: true

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - name: Maven Build
        run: |
          ./mvnw -B verify

      - name: Publish docker image to eu.gcr.io
        if: github.github.head_ref == null && success()
        run: |
          mvn -B -U -Pdocker package -DskipTests -Dimage.version=$SHA8

    outputs:
      image_version: ${{ steps.vars.outputs.sha_short }}