# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Non-Main-Compile-Test-Build-Image

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  setup-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Maven Build
        run: |
          ./mvnw -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 verify
        env:
          GITHUB_TOKEN: ${{ secrets.DEVBOT_GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          ./mvnw -B -Plocal package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.DEVBOT_GITHUB_TOKEN }}
